# Generated by Django 4.2.4 on 2023-11-09 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
                ('fecha_salida', models.CharField(max_length=20)),
                ('asientos_disponibles', models.PositiveIntegerField()),
                ('estado_actual', models.CharField(max_length=10)),
                ('chiva_asignada', models.CharField(max_length=20)),
                ('precio_asiento', models.FloatField()),
                ('conductor_asignado', models.CharField(max_length=20)),
            ],
        ),
    ]
