# Generated by Django 4.2.4 on 2023-11-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=20)),
                ('tecnomecanica', models.CharField(max_length=20)),
                ('numero_poliza', models.CharField(max_length=20)),
                ('reporte_daño', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viaje_reservado', models.CharField(max_length=20)),
                ('asientos_reservados', models.CharField(max_length=2)),
                ('nombre_titular', models.CharField(max_length=30)),
                ('identificacion_titular', models.CharField(max_length=15)),
                ('email_titular', models.CharField(max_length=20)),
                ('celular_titular', models.CharField(max_length=10)),
                ('direccion_titular', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReservasChivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
                ('fecha_contratada', models.CharField(max_length=20)),
                ('fecha_contratada_hasta', models.CharField(max_length=20)),
                ('chiva_asignada', models.CharField(max_length=20)),
                ('nombre_titular', models.CharField(max_length=30)),
                ('identificacion_titular', models.CharField(max_length=15)),
                ('email_titular', models.CharField(max_length=20)),
                ('celular_titular', models.CharField(max_length=10)),
                ('direccion_titular', models.CharField(max_length=30)),
                ('productos_adicionales', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Viajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.CharField(max_length=30)),
                ('fecha_salida', models.CharField(max_length=20)),
                ('asientos_disponibles', models.PositiveIntegerField()),
                ('estado_actual', models.CharField(max_length=10)),
                ('chiva_asignada', models.CharField(max_length=20)),
                ('precio_asiento', models.FloatField()),
                ('conductor_asignado', models.CharField(max_length=20)),
            ],
        ),
    ]
