# Generated by Django 4.2.4 on 2023-11-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viaje_reservado', models.CharField(max_length=20)),
                ('asientos_reservados', models.CharField(max_length=2)),
                ('nombre_titular', models.CharField(max_length=30)),
                ('identificacion_titular', models.CharField(max_length=15)),
                ('email_titular', models.CharField(max_length=20)),
                ('celular_titular', models.CharField(max_length=10)),
                ('direccion_titular', models.CharField(max_length=30)),
            ],
        ),
    ]
