# Generated by Django 4.2.4 on 2023-11-21 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cancelaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelaciones',
            name='asientos_devueltos',
            field=models.CharField(default=-1, max_length=10),
            preserve_default=False,
        ),
    ]
